# Site settings
title: Syed Irshad
subtitle: Homepage
tagline: This is tag line.
email: gsirshad.ai4@gmail.com
description: This is description. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gsirshad-source.gitlab.io" # the base hostname & protocol for your site
logo: assets/images/favicon.png
image: assets/images/og-pic.jpg


# Blog posts
words_per_minute : 160
future : true
read_more : "disabled"

# projects
collections:
    projects:
        output: true

myversion: 4.5.0

author:
    name: Syed Irshad
    avatar : assets/images/profile_picture.png
    avatar-webp: assets/images/profile_picture.webp
    avatar-thumb: assets/images/profile_picture-thumb.jpg
    # author-bio : "Incoming PhD Student at ICRAR/UWA Perth."
    author-bio : "author Bio."
    ads : 
    facebook: https://www.facebook.com/
    github: https://github.com/
    gitlab: https://gitlab.com/
    googleplus: 
    googlescholar : https://scholar.google.com/
    instagram: https://www.instagram.com/
    linkedin: https://www.linkedin.com/
    orcid: https://orcid.org/
    pinterest:
    researchgate: https://www.researchgate.net/
    slack:
    stackoverflow : https://stackoverflow.com/
    steam : https://steamcommunity.com/
    twitter: https://twitter.com/

# Social for SEO
twitter: 
  username: 
  card: summary_large_image

facebook:
  app_id: 
  publisher:    
  admins: 

social:
  name: Syed Irshad
  links:
    - https://twitter.com/
    - https://www.instagram.com/
    - https://www.facebook.com/
    - https://github.com/
    - https://gitlab.com/
    - https://www.linkedin.com/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gzip
  - jekyll-brotli
  - jekyll-redirect-from

# Build settings
markdown: kramdown



exclude:
  - vendor  
